### ISSUE TITLE
GoogleAuth menu not appearing in strapi

### ISSUE THREAD

**Issue by Tezyindia** [arjusmoon860/strapi-google-auth#1]
We are not getting the GoogleAuth menu in strapi to add Client ID, Client Secret & Redirect URL

**Comment by arjusmoon860** [comment]
Can you share the plugin config file?

**Comment by Tezyindia** [comment]
> Can you share the plugin config file?

module.exports = ({ env }) => ({
  email: {
    config: {
      provider: 'nodemailer',
      providerOptions: {
        host: env('SMTP_HOST', '***********'),
        port: env('SMTP_PORT', ******),
	secure: true,
        auth: {
          user: 'noreply@******',
          pass: 'Noreply@******',
        },
      },
      settings: {
        defaultFrom: 'noreply@*****',
        defaultReplyTo: 'noreply@*******',
      },
    },
	   'google-auth': {
        enabled: true,
    },
},
});
