### ISSUE TITLE
I am getting JsonWebTokenError for strapi-google-auth/me 

### ISSUE THREAD

**Issue by hkashlan** [arjusmoon860/strapi-google-auth#13]
I did Get Google Authentication URL:
```
   {
       method: 'GET',
       path: 'STRAPI_BACKEND_URL/strapi-google-auth/init',
   } 
```
then Authenticate User [I am using vscode rest](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
```
POST http://localhost:1337/strapi-google-auth/user-profile HTTP/1.1
content-type: application/json

{
    "code":"Code from step 1"
}

```

get the token from step 2 then call

```
GET http://localhost:1337/strapi-google-auth/me HTTP/1.1
authorization:Bearer token_from_step_2
```

but always getting JsonWebTokenError: invalid signature :( at node_modules/jsonwebtoken/verify.js:138:19

**Comment by FernadoLuna** [comment]
me pasa lo mismo, alguien ya lo soluciono?

**Comment by rockbenben** [comment]
Update the "dependencies" in the package.json file as follows:

```json
"dependencies": {
  "strapi-google-auth": "https://github.com/arjusmoon860/strapi-google-auth.git"
}
```

**Comment by arjusmoon860** [comment]
The plugin now works with the latest version of strapi & node 18.x.x. Please read the documentation given in the git repo.
Closing this issue for now. Please reopen if you are facing any issue.

Thanks.
