### ISSUE TITLE
Node 18 Support

### ISSUE THREAD

**Issue by z0lo13** [arjusmoon860/strapi-google-auth#14]

**Comment by kpetrillo** [comment]
Is this plugin dead?

**Comment by TorrealbaLR** [comment]
> Is this plugin dead?

seems like it

**Comment by arjusmoon860** [comment]
The plugin now works with the latest version of strapi & node 18.x.x. Please read the documentation given in the git repo.
Closing this issue for now. Please reopen if you are facing any issue.

Thanks.
