### ISSUE TITLE
Running yarn develop on Strapi 4.6.0 produces TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Antvirf** [arjusmoon860/strapi-google-auth#15]
Posting this in case anyone else runs into the same. I'm not sure if the proper fix is to update the docs, but this worked for me. I'm on `Node 18` and `Strapi 4.6.0`. (And yes at the time of writing this plugin doesn't officially support either..)

## Error
```
yarn develop
yarn run v1.22.19
warning ../../../package.json: No license field
$ strapi develop
Building your admin UI with development configuration...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:400:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:1098:7)
    at /Users/aviitala/dev-work/socially-responsible/strapi-proto/node_modules/@strapi/admin/utils/create-cache-dir.js:82:33
    at Array.filter (<anonymous>)
    at createCacheDir (/Users/aviitala/dev-work/socially-responsible/strapi-proto/node_modules/@strapi/admin/utils/create-cache-dir.js:80:6)
    at async Object.build (/Users/aviitala/dev-work/socially-responsible/strapi-proto/node_modules/@strapi/admin/index.js:27:3)
    at async primaryProcess (/Users/aviitala/dev-work/socially-responsible/strapi-proto/node_modules/@strapi/strapi/lib/commands/develop.js:62:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Fix 

Beyond what's given in the README, In your ```config/plugins.js``` add the below:
```js
  'google-auth': {
        enabled: true,
        resolve: "./node_modules/strapi-google-auth/" // resolves the issue
    },
```

**Comment by robmanganelly** [comment]
Same issue with Strapi  `4.6.1` and `Node 18`.  I got a dependency conflict when I tried to install using `pnpm`. After trying with `yarn`, I got the issue described above, and after trying many (silly) solutions, `yarn`  complaint that plugin didn't support installation with `Node 18` engine.

**Comment by Antvirf** [comment]
> Same issue with Strapi `4.6.1` and `Node 18`. I got a dependency conflict when I tried to install using `pnpm`. After trying with `yarn`, I got the issue described above, and after trying many (silly) solutions, `yarn` complaint that plugin didn't support installation with `Node 18` engine.

@robmanganelly `yarn` wasn't initially happy with this either (and of course I don't really know yet if this is supposed to work with node 18 anyway...), but I got it to install with:

```
yarn add strapi-google-auth --ignore-engines
```

**Comment by MokDevelopment** [comment]
I am on node/16.19.1 & Strapi 4.7.1
- Same issue. 

I also created a fresh blank strapi app:
- Same issue.

To me this looks more as if the plugin is not maintained / not compatible to Strapi 4.6.1 >

**Comment by MokDevelopment** [comment]
I happens when adding the details to the config:
  // "google-auth": {
  //   enabled: true,
  //   resolve: "./node_modules/strapi-google-auth/" // resolves the issue
  // },
  
  When not defined the issue seems to vanish.
  Still the plugin seems to be usable?!

**Comment by boogiebug** [comment]
Is it about the plugin folder should be in the format of ```strap-plugin-<plugin-name>```?

**Comment by joffreyBerrier** [comment]
To solve that put this in your plugins:
```javascript
module.exports = ({ env }) => ({
  'google-auth': {
    clientID: env('GOOGLE_CLIENT_ID'),
    clientSecret: env('GOOGLE_CLIENT_SECRET'),
    redirectUri: env('GOOGLE_REDIRECT_URI'),
  },
});

```

This is the key `enabled: true` it doesn't work

**Comment by arjusmoon860** [comment]
The plugin now works with the latest version of strapi & node 18.x.x. Please read the documentation given in the git repo.
Closing this issue for now. Please reopen if you are facing any issue.

Thanks.
