### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by am2222** [arjusmoon860/strapi-google-auth#4]
Hi,
While setting up the plugin I am getting this error
```
google-auth
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:363:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:167:9)
    at H:\LoyalAppProject\loyalbackend\node_modules\@strapi\admin\index.js:187:33
    at Array.filter (<anonymous>)
    at createCacheDir (H:\LoyalAppProject\loyalbackend\node_modules\@strapi\admin\index.js:184:6)
    at Object.build (H:\LoyalAppProject\loyalbackend\node_modules\@strapi\admin\index.js:59:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

I am on the latest version of strapi. 
I just install it using `yarn` and enable it in the plugins.js then run `yarn build` and face this error

**Comment by am2222** [comment]
it seems to enable plugin we need to add the following key to the plugins.js
```
        'strapi-google-auth': {
            enabled: true,
        },
```

**Comment by arjusmoon860** [comment]
Yes, it's mentioned in the documentation.

**Comment by jonathan-chin** [comment]
> Yes, it's mentioned in the documentation.

the documentation is miswritten. it says:
```
'google-auth': {
        enabled: true,
    },
```

note `google-auth` instead of `strapi-google-auth`. my team ran into the same issue.
the documentation on strapi market place has the same issue: https://market.strapi.io/plugins/strapi-google-auth

**Comment by alexblais** [comment]
Faced the same issue. You should update your doc @arjusmoon860
