### ISSUE TITLE
Google Auth doesn't display on the Login screen after everything is correctly setup

### ISSUE THREAD

**Issue by kevinblanco** [arjusmoon860/strapi-google-auth#7]
Hi, I'd like to understand how to get this to work on the login page, I installed the plugin correctly, followed the steps on the documentation, generated the Auth API keys and secret, configured the consent screen, the plugin shows on my plugin dashboard in strapi, but when I logout I still get the standard username/password strapi login. 

What do I need to do to show the Google Auth?

**Comment by arjusmoon860** [comment]
Hey @kevinblanco This is not a google auth functionality for the Admin. You can use these APIs to build a custom functionality in the frontend of your website for users to sign up using google. The data will get stored in the Strapi database, and you can easily manage access of the users.
