### ISSUE TITLE
Get Google Authentication URL dosen't return the REDIRECTION_AUTH_CODE

### ISSUE THREAD

**Issue by CypYouOnline** [arjusmoon860/strapi-google-auth#8]
I actually try to integrate google auth in my app but when i request `STRAPI_BACKEND_URL/strapi-google-auth/init` the `REDIRECTION_AUTH_CODE` is not present in the url :
`https://accounts.google.com/o/oauth2/v2/auth?access_type=off…usercontent.com&redirect_uri=https%3A%2F%2Freview-rewards.fr`
(At the first step...)

**Comment by arjusmoon860** [comment]
You will get the redirection auth code on the URL after a successful google login. Google will automatically redirects the user to the redirection URL you have provided with a parameter called "code". 

In your case, it will be https://review-rewards.fr?code=GOOGLE_AUTH_CODE

GOOGLE_AUTH_CODE will get appended to the redirect URL by google.
