### ISSUE TITLE
path: 'STRAPI_BACKEND_URL/strapi-google-auth/init' return 400 (Bad Request)

### ISSUE THREAD

**Issue by smartfox87** [arjusmoon860/strapi-google-auth#9]
STRAPI VERSION v4.4.3
 "strapi-google-auth": "^0.1.2",

[screenshot error from console](https://disk.yandex.com/d/uINCG-jN3y05ww)
and server shows error too
[screnshot server error](https://disk.yandex.com/d/bmew4C3ogKMaqQ)
[my plugin settings](https://disk.yandex.com/d/HMgIPHBq2o9qxA)
after saving settings value scopes looks wrong
[screen](https://disk.yandex.com/d/mlaHJU3y9S39og)
because of this, an error occurs in the plugin
[error server screenshot](https://disk.yandex.com/d/RWbRLszk68FXeQ)
which I fixed in file node_modules/strapi-google-auth/server/services/google.js
[fixed error screenshot](https://disk.yandex.com/d/JDzE3oFWOPspiQ)

**Comment by andrybicio** [comment]
Same error here. Solved thanks to smartfox87 comment

**Comment by arjusmoon860** [comment]
The plugin now works with the latest version of strapi & node 18.x.x. Please read the documentation given in the git repo.
Closing this issue for now. Please reopen if you are facing any issue.

Thanks.
